name: http_mock
version: 1.1.0
description: A package:http client that can mock server responses.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/http_mock
environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"
dependencies:
  angel_route: ^3.0.0
  http: "^0.11.3+17"
dev_dependencies:
  test: ^1.0.0
